Update ftl pageBuilder
craftercms/wordify-blueprint pull request #37
Opened 2021-06-07 22:20 UTC by jvega190

2021-06-08 18:08 UTC, jvega190 commented on craftercms-plugin.yaml
>    version:
Older versions already removed

2021-06-08 18:19 UTC, jvega190 commented on config/studio/content-types/component/post/form-definition.xml
> +							<value>,/component/bio</value>
It was due to outdated files, re-added the control and now the leading commas are not there

2021-06-18 17:28 UTC, jvega190 commented
Screenshot for this ticket https://github.com/craftercms/craftercms/issues/4671 is in this PR

2021-06-23 17:11 UTC, rart requested changes

2021-06-23 17:11 UTC, rart commented on config/studio/ui.xml
> +<?xml version="1.0" encoding="UTF-8" ?>
Outdated xml

2021-06-23 19:21 UTC, jvega190 commented
@rart updates done in here https://github.com/craftercms/wordify-blueprint/pull/39 moved to this PR, and reviews for that PR are done in here too

2021-06-24 06:30 UTC, rart requested changes

2021-06-24 06:30 UTC, rart commented on templates/web/fragments/footer.ftl
> +<@crafter.tag $tag="footer" $model=contentModel class="site-footer">
crafter.tag

2021-06-28 16:55 UTC, rart approved these changes

2021-06-29 23:48 UTC, sumerjabri commented
@rart why are we moving away from the `crafter` namespace?

2021-06-30 04:54 UTC, rart commented
@jvega190 what we discussed was extracting navigation out of ice.ftl, not out of crafter.ftl

fyi @sumerjabri

2021-07-01 10:17 UTC, rart approved these changes

2021-07-14 12:47 UTC, merged