Improvements for search - react app
craftercms/wordify-blueprint pull request #44
Opened 2021-07-01 16:52 UTC by jvega190

- Add support for exact matches using quotes
- Add support for field boosting to improve search results

https://github.com/craftercms/craftercms/issues/3160

2021-07-15 14:02 UTC, rart requested changes
Please correct indentation of the xml changes.

2021-07-15 14:02 UTC, rart commented on config/studio/workflow/notification-config.xml
> +<!--            <email>admin2@example.com</email>-->
```suggestion
             <!--<email>admin@example.com</email>-->
             <!--<email>admin2@example.com</email>-->
```

2021-07-15 14:02 UTC, rart commented on config/studio/workflow/notification-config.xml
> +<!--            <email>admin2@example.com</email>-->
```suggestion
             <!--<email>admin@example.com</email>-->
             <!--<email>admin2@example.com</email>-->
```

2021-07-15 14:02 UTC, rart commented on config/studio/workflow/notification-config.xml
> +<!--            <email>admin2@example.com</email>-->
```suggestion
             <!--<email>admin@example.com</email>-->
             <!--<email>admin2@example.com</email>-->
```

2021-08-04 23:08 UTC, jvega190 commented
@rart this is ready for merge

2021-08-05 22:06 UTC, rart reviewed
Version upgrade performed.

@jvega190 changes for next?

2021-08-05 22:07 UTC, rart approved these changes
Version upgrade performed.

@jvega190 changes for next?

2021-08-05 22:11 UTC, jvega190 commented
Already done/merged in https://github.com/craftercms/wordify-blueprint/commit/2ce985819dd0f93034ffd79746b03fad2639e195 (react) and https://github.com/craftercms/wordify-blueprint/commit/8a19ee456698f204679ae2c28d5dbd778e3012fc (freemarker)

2021-08-06 13:41 UTC, merged